In [12]:
import numpy as np

In [11]:
arr = np.random.randint(1, 101, size=(5, 5))  #original array
print(arr)

[[15  5 89 44 66]
 [51 90 95 20 93]
 [82 64 15 71 81]
 [76 57 64 57 38]
 [53 29 46  9 79]]


In [10]:
print(arr[2, 2]) #middle

98


In [9]:
print(np.mean(arr, axis=1))

[42.4 83.4 61.4 30.4 55.6]


In [8]:
overall_mean = np.mean(arr)
print(overall_mean)
print(arr[arr > overall_mean])

54.64
[100  95  98  85  57  99  78  98  57  81  90  68  89  59  56]


In [13]:
def numpy_spiral_order(matrix):
    result = []
    top, bottom = 0, matrix.shape[0] - 1
    left, right = 0, matrix.shape[1] - 1

    while top <= bottom and left <= right:
        for i in range(left, right + 1):
            result.append(matrix[top, i])
        top += 1

        for i in range(top, bottom + 1):
            result.append(matrix[i, right])
        right -= 1

        if top <= bottom:
            for i in range(right, left - 1, -1):
                result.append(matrix[bottom, i])
            bottom -= 1

        if left <= right:
            for i in range(bottom, top - 1, -1):
                result.append(matrix[i, left])
            left += 1

    return result

In [14]:
print("Spiral order:", numpy_spiral_order(arr))

Spiral order: [15, 5, 89, 44, 66, 93, 81, 38, 79, 9, 46, 29, 53, 76, 82, 51, 90, 95, 20, 71, 57, 64, 57, 64, 15]
